# -*- coding: utf-8 -*-
"""24bit025 - Final ML Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_85uLlytQdlbIY4YJG1qOKXWDX_jsHR

#File Upload
"""

import pandas as pd
from google.colab import files

up=files.upload()

data=pd.read_csv('Delivery_Logistics.csv')

"""#Data Frame"""

df=pd.DataFrame(data)
df

"""#Data Preprocessing and Data Cleaning"""

df.info()

df.describe()

df.isnull()

df.duplicated()

df.duplicated().sum()

df.isnull().sum()

group1=df.groupby('delivery_mode')['delivery_cost'].sum()

"""#Bar Chart"""

import matplotlib.pyplot as plt
plt.bar(group1.index, group1.values)
plt.xlabel("DELIVERY MODE")
plt.ylabel("DELIVERY COST")
plt.title("MODE VS COST")
plt.show()

group2=df.groupby('region')['distance_km'].sum()

"""#Plot"""

plt.plot(group2)
plt.xlabel("REGION")
plt.ylabel("DISTANCE KM")
plt.xticks(rotation=45)
plt.title("REGION vs DISTANCE")
plt.show()

group3=df.groupby('vehicle_type')['package_weight_kg'].sum()

"""#Scatter"""

plt.scatter(group3.index, group3.values)
plt.xlabel("VEHICLE TYPE")
plt.ylabel("PACKAGE WEIGHT")
plt.xticks(rotation=45)
plt.title("VEHICLE TYPE VS PACKAGE WEIGHT ")
plt.show()

"""#Histogram"""

plt.hist(df['delivery_time_hours'],bins=20)
plt.xticks(rotation=45)
plt.title("delivery_time_hours")
plt.show()

"""#Pie Chart"""

import pandas as pd
import matplotlib.pyplot as plt
site_name_counts = df['region'].value_counts()
plt.pie(site_name_counts, labels=site_name_counts.index, autopct='%1.1f%%')
plt.title("Distribution of Site Names")
plt.legend()
plt.show()

"""#Dashboard To Visuvalize The Entire Data"""

plt.figure(figsize=(20,17))
plt.suptitle("My Dashboard",fontsize=15)
plt.subplot(3,2,1)
plt.bar(group1.index, group1.values)
plt.xlabel("DELIVERY MODE")
plt.ylabel("DELIVERY COST")
plt.title("MODE VS COST")
plt.subplot(3,2,2)
plt.plot(group2)
plt.xlabel("REGION")
plt.ylabel("DISTANCE KM")
plt.xticks(rotation=45)
plt.title("REGION vs DISTANCE")
plt.subplot(3,2,3)
plt.scatter(group3.index, group3.values)
plt.xlabel("VEHICLE TYPE")
plt.ylabel("PACKAGE WEIGHT")
plt.xticks(rotation=45)
plt.title("VEHICLE TYPE VS PACKAGE WEIGHT ")
plt.subplot(3,2,4)
plt.hist(df['delivery_time_hours'],bins=20)
plt.xticks(rotation=45)
plt.title("delivery_time_hours")
plt.subplot(3,2,5)
import pandas as pd
import matplotlib.pyplot as plt
site_name_counts = df['region'].value_counts()
plt.pie(site_name_counts, labels=site_name_counts.index, autopct='%1.1f%%')
plt.title("REGIONS")
plt.legend()
plt.tight_layout(rect=[0, 0.03, 1, 0.95])

"""#ML Model"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

df

"""#Encoding the Unique Value To Machine Understandable Formate"""

df['vehicle_type_encoded'] = pd.factorize(df['vehicle_type'])[0]
df['delivery_mode_encoded'] = pd.factorize(df['delivery_mode'])[0]
df['weather_condition_encoded'] = pd.factorize(df['weather_condition'])[0]
df['region_encoded'] = pd.factorize(df['region'])[0]
df[['vehicle_type', 'vehicle_type_encoded', 'delivery_mode', 'delivery_mode_encoded', 'region', 'region_encoded', 'weather_condition', 'weather_condition_encoded']].head()

"""#Value Assigning"""

x=df[['region_encoded','distance_km','package_weight_kg','delivery_cost','delivery_id']]

y=df['delivery_mode_encoded']

x

y

"""#Split The Values For Both Train And Test"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.02, random_state=42)

"""#Model Selection and Fitting The Variables"""

model=RandomForestClassifier()

model.fit(x_train,y_train)

"""#Predicting the Test Values"""

y_pred=model.predict(x_test)

y_test

"""#Evaluating The ML model"""

print(accuracy_score(y_pred,y_test))

"""#Testing With New Values"""

raw=np.array([[0.0, 257.995871, 1.875005, 195.60321, 3389.921818]])

model.predict(raw)

"""#Confution Matrix and HeatMap"""

cm=confusion_matrix(y_pred,y_test)

import seaborn as sns
sns.heatmap(cm, annot=True)

"""#Real World Example With User Input And Machine Predictions"""

delivery_mode_mapping = {
    0: 'same day',
    1: 'express',
    2: 'two day',
    3: 'standard'
}
try:
    input_region_encoded = int(input("Enter region_encoded (e.g., 0 for west, 1 for central, 2 for east, 3 for north): "))
    input_distance_km = float(input("Enter distance_km (e.g., 150.0): "))
    input_package_weight_kg = float(input("Enter package_weight_kg (e.g., 20.0): "))
    input_delivery_cost = float(input("Enter delivery_cost (e.g., 500.0): "))
    input_delivery_id = float(input("Enter delivery_id (e.g., 12345.0): "))
except ValueError:
    print("Invalid input. Please enter numeric values.")
    exit()

user_input = pd.DataFrame([{
    'region_encoded': input_region_encoded,
    'distance_km': input_distance_km,
    'package_weight_kg': input_package_weight_kg,
    'delivery_cost': input_delivery_cost,
    'delivery_id': input_delivery_id
}])
predicted_encoded_mode = model.predict(user_input)
predicted_delivery_mode_word = delivery_mode_mapping.get(predicted_encoded_mode[0], 'Unknown')

print(f"\nInput values: {user_input.to_string(index=False)}")
print(f"Predicted Delivery Mode: {predicted_delivery_mode_word}")

import pickle

with open("model.pkl","wb") as f:
  pickle.dump(model,f)

from google.colab import files
files.download("model.pkl")